# Generated by Django 3.1.1 on 2020-09-08 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2020, 9, 8, 9, 4, 50, 863733))),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='video')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 9, 4, 50, 863733))),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
            ],
        ),
    ]
