# Generated by Django 3.1.1 on 2020-09-08 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.FileField(upload_to='video')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 12, 40, 12, 363324))),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 12, 40, 12, 363324))),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 12, 40, 12, 347724)),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.topic'),
        ),
    ]
